notifications:
  email: false

sudo: false

language: php

php:
  - 7.2
  - 7.4

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer validate
  - composer --no-interaction update --no-progress --no-suggest $DEPENDENCIES

script:
  - composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls:^2
  - vendor/bin/php-coveralls -v
